[package]
name = "auther"
description = "a terminal password manager"

version = "1.1.0"
edition = "2021"

license = "MIT"

[workspace]

[dependencies]
sarge = "2.0"
auther-lib = { path = "auther-lib", features = ["serde"] }
dirs = "4.0.0"
magic-crypt = "3.1"
eframe = "0.21"
toml = "0.7"
