[package]
name = "auther"
description = "a password manager, both lib and bin"

version = "1.0.0"
edition = "2021"

license = "MIT"

[dependencies]
rand_core = "0.6.4"
rand_hc = "0.3.1"
sha2 = "0.10.6"